import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import FooterComponent from "../src/components/common/FooterComponent";
import MarginLayout from "../src/components/common/MarginLayout";
import StartPage from "../src/components/startpage/StartPage";
import styles from "../styles/Home.module.css";
import prosjektdata from "../src/data/prosjekterdata";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kjetil Øverby • Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MarginLayout>
        <StartPage />
      </MarginLayout>
      <FooterComponent data={prosjektdata} header="hovedprosjekter" />
    </div>
  );
};

export default Home;
